### ISSUE TITLE
Throws 'Pattern not found: ths' on use

### ISSUE THREAD

**Issue by tankorsmash** [statox/vim-compare-lines#1]
I've got a new unsaved buffer with

asd asd asd
asd Asd asd

and my cursor is on line 1 col 1, and I use `:CL` with no args, I get the following error

```
search hit BOTTOM, continuing at TOP
Error detected while processing function <SNR>55_PreTreatmentFunction[46]..<SNR>55_CompareLines:
line   24:
E486: Pattern not found: ths

```

Disabled all plugins but this one, and still had the issue. Vim 7.4 1-1689

**Comment by statox** [comment]
As this is a small side project I totally forgot about this issue, sorry about that!

There was two problem: the comparison of the characters wasn't made properly and thus lowercase and uppercase letters were considered as identical. The second issue was that identical lines weren't handled properly and gave an error message. Both problems should be fixed now.

**Comment by tankorsmash** [comment]
Thank you!
